# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lukas Muttenthaler
email: _
description: >- # this means to ignore newlines until "baseurl:"
  PhD student in Machine Learning at the Department of Software Engineering and Theoretical Computer Science, TU Berlin, 
  working on using human inductive biases to align and improve neural network representations, 
  with a focus on low data regimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lukasmut.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lukas_mut
github_username:  LukasMut

author:
  name: Lukas Muttenthaler

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/LukasMut" }
    - { platform: twitter, user_url: "https://twitter.com/lukas_mut" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/lukas-muttenthaler/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=ktyApiAAAAAJ&hl=en&oi=ao" }

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

logo: images/image_01.jpg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
